name: Deploy SpiderMan Trivia Website (Frontend)

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Spiderman Secrets
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      AWS_REGION: 'eu-west-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy frontend directory
        run: aws s3 sync frontend/ s3://${{ env.BUCKET_NAME }} --delete
