name: Database Migration with Flyway

on:
  push:
    branches: 
      - "main"
      - "feature/arinaho/database-flyway-cicd"
    paths:
      - 'database/scripts/**'
      - 'database/flyway/**'

  workflow_dispatch:

jobs:
  migrate-database:
    name: Run Flyway Migration
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate flyway config file with secrets
      run: |
        echo "flyway.url=${DB_URL}" >> flyway.generated.conf
        echo "flyway.user=${DB_USERNAME}" >> flyway.generated.conf
        echo "flyway.password=${DB_PASSWORD}" >> flyway.generated.conf
        cat database/flyway/flyway.conf >> flyway.generated.conf
        cat flyway.generated.conf  # Print contents of the generated config file

    - name: Run Flyway Migration
      run: |
        sudo snap install flyway
        flyway migrate -configFiles=flyway.generated.conf
