name: Database Migration with Flyway

on:
  push:
    branches: 
      - "main"
      - "feature/arinaho/database-flyway-cicd"
    paths:
      - 'database/scripts/**'

  workflow_dispatch:

jobs:
  migrate-database:
    name: Run Flyway Migration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy flyway config file
      run: cp database/flyway/flyway.conf flyway.conf

    - name: Run Flyway Migration
      run: |
        sudo snap install flyway
        flyway migrate -configFiles=database/flyway/flyway.conf
